---
title: "COVID-19 Weekly Dashboard"
# author: "Wei Fu"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  flexdashboard::flex_dashboard:
    css: custom.css
    orientation: rows
    social: menu
    source_code: embed
    logo: MIB_logo.png
    # theme: flatly
    # theme: united
    # theme: cosmo
    theme: spacelab
    vertical_layout: scroll
# runtime: shiny
---
```{r setup, include=FALSE}


library(highcharter)
library(tidyverse)
library(viridisLite)
library(forecast)
library(treemap)
library(flexdashboard)
library(dygraphs)
library(xts)
library(colorspace)
library(lubridate)

library(knitr)
library(kableExtra)
library(scales)

thm <- 
  hc_theme(
    # colors = c("#1a6ecc", "#434348", "#90ed7d"),
    # colors = rainbow_hcl(3),
    colors = c("#E495A5", "#86B875", "#7DB0DD"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Verdana")
      #Source Sans Pro
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )

library(readxl)
Base <- read_excel("D:/Product/Base.xlsx", 
     col_types = c("numeric", "numeric", "numeric", 
         "date", "numeric", "numeric", "date", 
         "numeric", "numeric", "date", 
         "numeric", "numeric", "numeric", 
         "numeric"))

library(stringr)
#remove space in the cloumn names
names(Base)<- str_replace_all(names(Base), c("\\\r\\\n" = "." , "," = "", " "="_" ))

B<- Base[, c("Current.Date", "Current_Yr.Inquiries", "Prior_Yr.Inquiries", "Prior_2_Yr.Inquiries")]
colnames(B)<-c("dt", "cur_cnt", "pr_cnt", "pr2_cnt")

#an xts object can only have numberic data in it. Make sure to remove the date column because it will be converted to a character data type
# B[, 2:4], B[, -1], B[c(-1)] are equivalent here
ts<- xts(B[, 2:4], as.Date(B$dt))

```


<!-- Weekly -->
<!-- =====================================  -->

Row {data-height=600}
-----------------------------------------------------------------------

### Moving Average Comparison
This chart shows 7-day moving averages of inquiries. Slide the levers to zoom or move the time window. Hover to see the data values by year.

```{r}

# colnames(ts)<-c("2020", "2019", "2018")
# plot.xts(ts, col=c("red", "blue", "orange"), bg="grey87", main=NULL, legend.loc = "topleft")
# #main=NULL or "" gets rid of the series name 
# title(main="Daily Count")

#line up dates by week number and week day
#week and wday are functions in package lubridate
d1 <-data.frame(DATE=Base$Current.Date, WK=epiweek(Base$Current.Date), WD=wday(Base$Current.Date), CNT2020=Base$Current_Yr.Inquiries)
d2 <-data.frame(WK=epiweek(Base$Prior_Yr.Date), WD=wday(Base$Prior_Yr.Date), CNT2019=Base$Prior_Yr.Inquiries)
d3 <-data.frame(WK=epiweek(Base$Prior_2_Yr.Date), WD=wday(Base$Prior_2_Yr.Date), CNT2018=Base$Prior_2_Yr.Inquiries)

# make 12/29/2019 week 53 instead of week 1
flag<-(as.numeric(rownames(d2))>max(as.numeric(rownames(d2[which(d2$WK==52), ]))))
d2[(flag),]$WK <- d2[(flag),]$WK + 52

flag2<-(as.numeric(rownames(d3))>max(as.numeric(rownames(d3[which(d3$WK==52), ]))))
d3[(flag2), ]$WK<-d3[(flag2),]$WK +52

#join by week number and week day, Feb 29 is not a problem
cmb<- left_join(d1, d2, by=c("WK", "WD")) %>% 
  left_join(d3, by=c("WK", "WD"))

cmb_ts <- xts(cmb[, c(2:6)], as.Date(cmb$DATE))

#create 7-day moving average
ma<-stats::filter(cmb_ts[, 3:5], filter=c(1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7), sides=1)
ma<-xts(ma, as.Date(cmb$DATE))

#append dates to ma
ma_xts <- xts(cbind(cmb_ts, ma), as.Date(index(cmb_ts)))
#give names to MA columns
colnames(ma_xts)[6:8]<-c("MA_CUR", "MA_PR", "MA_PR2")
a<- mean(ma_xts$MA_CUR, na.rm=TRUE)
ma_xts$MA_CUR_R <- 100*ma_xts$MA_CUR/a
ma_xts$MA_PR_R <- 100*ma_xts$MA_PR/a
ma_xts$MA_PR2_R <- 100*ma_xts$MA_PR2/a

#ma chart, multiple series
highchart(type="stock") %>% 
  # hc_xAxis(categories=as.Date(index(ma_xts), format="%d %b %Y")) %>%
  # hc_title(text="7-Day MA By Year", style=(list(fontFamily = "Helvetica")))  %>%
  hc_xAxis(minRange=1) %>%
  hc_yAxis(labels=(list(format='{value}%'))) %>%
  # hc_add_series(name="2020", data=ma_xts$MA_CUR, dataLabels =list(enabled = TRUE, format='{point.y:.2f}')) %>%
  hc_add_series(name="2020", data=ma_xts$MA_CUR_R, showInLegend = TRUE) %>% 
  hc_add_series(name="2019", data=ma_xts$MA_PR_R) %>%
  hc_add_series(name="2018", data=ma_xts$MA_PR2_R) %>%
  hc_annotations(
    list(
      labelOptions = list(
      backgroundColor = 'rgba(255,255,255,0.5)',
      verticalAlign = 'top',
      y = 10,
      shape = "callout",
      fill = "none"
    ),
      labels = list(
               list(point = list(x =datetime_to_timestamp(as.Date("2020-04-10")), y = 85, xAxis = 0, yAxis = 0), text = "2020 Good Friday"),
               list(point = list(x = datetime_to_timestamp(as.Date("2020-05-25")), y = 80, xAxis = 0, yAxis = 0), text = "2020 Memorial Day")
      )
    )
  ) %>%
  hc_tooltip(pointFormat = "<span style=\"color:{series.color}\">{series.name}</span>: {point.y:.2f}%") %>%
  hc_add_theme(thm)

```

Row {data-height=600}
-----------------------------------------------------------------------

### MA YOY Comparison

This chart shows the 7-day moving average of this year compared to that of the prior year.
```{r}


#ratio of 2020 over 2019; append index from cm_ts because they have the same length
r1 <- xts(ma[,1]/ma[,2], as.Date(index(cmb_ts)))

r1 %>% 
  # forecast(level = 90) %>% 
  hchart(color="orangered", style=(list(fontFamily = "Verdana"))) %>%
  # {"fontFamily": "\"Lucida Grande\", \"Lucida Sans Unicode\", Verdana, Arial, Helvetica, sans-serif","fontSize":"12px"}.
  hc_title(text="7-Day MA YOY%", style=(list(fontFamily = "Helvetica"))) 

```


Row {.tabset .tabset-fade data-height=800}
-------------------------------------


### Weekly Changes

```{r}
#calculate weekly ratios
wkly <- subset(ma_xts, WD==7, select = c(WK, WD, MA_CUR, MA_PR, MA_PR2))
wkly$MA_YOY <- (wkly$MA_CUR/wkly$MA_PR)-1

wkly$MA_PRV_WK <-lag.xts(wkly$MA_CUR, k=1)
wkly$MA_WOW <- (wkly$MA_CUR/wkly$MA_PRV_WK)-1

#percent_format only accepts numeric data type not xts
p<- data.frame(cbind(as.numeric(wkly$WK), percent_format(accuracy=0.1)(as.numeric(wkly$MA_YOY)), percent_format(accuracy=0.1)(as.numeric(wkly$MA_WOW))))
colnames(p)<-c("WK", "MA_YOY_PCT", "MA_WOW_PCT")


p %>%
subset(MA_YOY_PCT!="NA%", select=c(WK, MA_YOY_PCT, MA_WOW_PCT)) %>%
  knitr::kable(caption="% Change in Weekly Average", escape = FALSE, col.names=c("Week", "Year Over Year %", "Over Previous Week %"),row.names = FALSE, align="c") %>%
  kable_styling(fixed_thead = list(enabled = T, background = "skyblue"), bootstrap_options=c("striped", "hover", "condensed", "responsive")) %>%
  # fixed_header = list(enabled = T, background = "black")  
  column_spec(2, bold = T, border_right = F) 

```

### YTD YOY By Week {data-height=350}

```{r}
B$pr_cnt[which(B$dt==as.Date("2020-02-29"))]<-0
B$pr2_cnt[which(B$dt==as.Date("2020-02-29"))]<-0
B$WK<-epiweek(B$dt)
B$WD<-wday(B$dt)
B$CUR_YTD<-cumsum(B$cur_cnt)
B$PR_YTD <-cumsum(B$pr_cnt)
B$YTD_YOY<- percent_format(accuracy=0.01)(as.numeric((B$CUR_YTD/B$PR_YTD)-1))

B[which(B$WD==7), ] %>%
subset(!is.na(CUR_YTD), select=c(dt, WK, YTD_YOY)) %>%
  knitr::kable(caption="YOY Change By Week", escape = FALSE, col.names=c("Date","Week", "YTD YOY %"), row.names = FALSE, align = "c") %>%
  kable_styling(fixed_thead = list(enabled = T, background = "skyblue"), bootstrap_options=c("striped", "hover", "condensed", "responsive")) %>%
  # fixed_header = list(enabled = T, background = "black")  
  column_spec(2, bold = T, border_right = F) 

```

